### ISSUE TITLE
GA set to storage:none when audience hits the dismiss button

### ISSUE THREAD

**Issue by isaactopo** [manucaralmo/GlowCookies#2]
Hi, 
it would be great to have the option, when someone rejects cookies, to be able to set GA anyway with the ```storage: none``` option.
As explained here: http://elnostreraco.com/labs/ga-cookies/cookies.php
So you would continue to have some data without breaching the GDPR.
Thanks.

**Comment by manucaralmo** [comment]
Thanks for the report. I'm already working on an update to fix the problem
