### ISSUE TITLE
Functionality questions

### ISSUE THREAD

**Issue by gracehcoote** [manucaralmo/GlowCookies#23]
Hi there, I have a couple of questions about how this plugin works. I can see in the settings details that you must add the Google Analytics tracking code in there as an option - my question is, does this mean I should not place the full tracking snippet that Analytics supplies onto the site itself? Does using this plugin with just the GA code add in the full tracking code if a user accepts?

My second question is regarding what happens once the cookies are accepted and the cookie bar disappears. This is the setup I use as it keeps the page clean, however my question is, what if the user wants to change their cookie preferences afterwards? If I were to include on the Cookie Policy page a checkbox which the user can untick, is there a way to use this to unset the preferences set in the plugin?

Thanks in advance!

**Comment by ru-ka** [comment]
> Hi there, I have a couple of questions about how this plugin works. I can see in the settings details that you must add the Google Analytics tracking code in there as an option - my question is, does this mean I should not place the full tracking snippet that Analytics supplies onto the site itself? Does using this plugin with just the GA code add in the full tracking code if a user accepts?

From what I've seen, it works exactly as you described.

**Comment by ru-ka** [comment]
> My second question is regarding what happens once the cookies are accepted and the cookie bar disappears. This is the setup I use as it keeps the page clean, however my question is, what if the user wants to change their cookie preferences afterwards? 

You can, [as described in the README.MD](https://github.com/manucaralmo/GlowCookies#config-banner), set `hideAfterClick` to false in order to let the window of GlowCookies stay minimized after refusal or consent.

> If I were to include on the Cookie Policy page a checkbox which the user can untick, is there a way to use this to unset the preferences set in the plugin?

As shown [here](https://github.com/manucaralmo/GlowCookies/blob/master/src/glowCookies.js#L109), GlowCookies uses the [local storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) in order to store cookies consent preferences. I think you can build a simple script that can modify/read this propriety. The key is `GlowCookies`, value `1` represents that consent has been given and value `0` represents that consent has been refused.

**Comment by gracehcoote** [comment]
Hi there, thanks for taking the time to reply!

> You can, [as described in the README.MD](https://github.com/manucaralmo/GlowCookies#config-banner), set `hideAfterClick` to false in order to let the window of GlowCookies stay minimized after refusal or consent.

Yes I was aware of this setting, but didn't actually want the Cookie box to always be visible.

> As shown [here](https://github.com/manucaralmo/GlowCookies/blob/master/src/glowCookies.js#L109), GlowCookies uses the [local storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) in order to store cookies consent preferences. I think you can build a simple script that can modify/read this propriety. The key is `GlowCookies`, value `1` represents that consent has been given and value `0` represents that consent has been refused.

Thanks for this, I'll have a better look into it and see what I can put together!
