### ISSUE TITLE
Cannot set property 'onclick' of null

### ISSUE THREAD

**Issue by isaactopo** [manucaralmo/GlowCookies#4]
I'm seeing this error `Uncaught TypeError: Cannot set property 'onclick' of null` on the console.

![Captura de pantalla 2020-11-30 a las 15 47 03](https://user-images.githubusercontent.com/4568596/100624400-b6485e00-3323-11eb-807b-6df505bd05e3.png)

**Comment by manucaralmo** [comment]
Thanks for the report, maybe a solution would be to add `"window.onload = function(){ }"`. I will work on it to bring a solution. 
If you feel comfortable modifying the code, you can make a pull request too.
Thank you!

**Comment by isaactopo** [comment]
Sorry but this solution doesn't work for me

**Comment by manucaralmo** [comment]
Hi! I just added a new update. Can you try now?

**Comment by isaactopo** [comment]
Hi @manucaralmo it's working now without errors, thanks!
