### ISSUE TITLE
German spelling not correct 

### ISSUE THREAD

**Issue by ReinholdH** [manucaralmo/GlowCookies#48]
The German bannerDescription in glowCookies.js is
'Wir nutzen Eigene und Cookies Dritter um Inhalte zu personalisieren und Surfverhalten zu analysieren.'
but the correct spelling has to be 
'Wir nutzen eigene und Cookies Dritter, um Inhalte zu personalisieren und Surfverhalten zu analysieren.'
See: "eigene" instead of "Eigene" and the comma before "um"

**Comment by ueen** [comment]
Yea, would you mind opening a PR?

**Comment by scsskid** [comment]
fixed the comma, added more well rounded translation
so also no need for discussion for how to spell "eigene" (some say its treated as a noun in this context, not a pronoun), nouns are capitalized German

PR: https://github.com/manucaralmo/GlowCookies/pull/49

**Comment by ReinholdH** [comment]
Thanks. Perfect.
