### ISSUE TITLE
Create option to let banner disappear after user agrees / rejects

### ISSUE THREAD

**Issue by smaxx1337** [manucaralmo/GlowCookies#6]
It would be cool to have an boolean option that the banner disappears, after the user rejects or accepts the cookies. 

Constantly having a cookie banner on your left / right can be annoying. 

A setting called disappearAfterAction = 'true' / 'false' would be enough. If true, maybe do display: none; on the button element.

Thank you very much!

**Comment by manucaralmo** [comment]
Nice Job!
